### ISSUE TITLE
Duplication of Manual Stateful and Stateless Stay-ON Switches

### ISSUE THREAD

**Issue by perfecblue** [Jason-Morcos/homebridge-magic-occupancy#1]
Hi, thanks for creating this plugin, I'm still learning the best way to use it and have the following question:

When I set the number of Stateful Manual Switches and Stateless Trigger Switches (the top two kinds), the bottom two Stay-ON Switches always seem to just replicate the exact numbers of the two top Switches for some reason.  It doesn't matter if I enter zero or negative numbers for the Stay-ON Switches, they always show up as the exact same number as their counterpart. 

It's only when I leave everything as 1 I'd get 4 switches.  But if i entered: 2, 2, 0, 0, I'd get eight switches showing up as 2, 2, 2, 2.

Is this by design or am I missing something here?

Thank you for the hard work!

**Comment by Jason-Morcos** [comment]
Good catch, it was a bug and I should have just fixed it in the newly-released 2.1.15. Give it a try and let me know if the issue persists after updating!

**Comment by perfecblue** [comment]
Think this duplication issue is resolved in v2.1.15, thanks!
