### ISSUE TITLE
Log

### ISSUE THREAD

**Issue by Christian-CFP** [Jason-Morcos/homebridge-magic-occupancy#12]
Hi,

so why is this (occupation timer stopped) showing up several times?

18:12:08 Occupancy Bridge Eingang Cancel timer and set occupancy to "NotDetected"
18:12:08 Occupancy Bridge Eingang Delay timer stopped
18:12:08 Occupancy Bridge Eingang Max occupation timer stopped
18:12:08 Occupancy Bridge Eingang Max occupation timer stopped
18:12:08 Occupancy Bridge Eingang Max occupation timer stopped
18:12:08 Occupancy Bridge Eingang Max occupation timer stopped
18:12:08 Occupancy Bridge Eingang checkOccupancy result: false. Previous occupied state: false, current state: false

**Comment by Jason-Morcos** [comment]
Likely an issue with order of ops. Plug-in is canceling the max timer before initiating un-occupancy so it's toggling the time on and off a few times in the disengagement process.
This kind of thing is totally harmless and certainly an improvement that could be made, but not something to worry about.
Are you having an issue of some sort? What prompted digging through the exact log messages from the plug-in? Really those are just for debugging issues.

**Comment by Christian-CFP** [comment]
No issue. Just wondering ;)
