### ISSUE TITLE
Dimmed light goes 100% ?

### ISSUE THREAD

**Issue by Pblondin123** [Jason-Morcos/homebridge-magic-occupancy#13]
Hi, i have some automation which will turn some lights at 5% when waking up for exemple.    Turns out that using the magic occupancy plugin they go full 100% (which really wakes us up!).   Any idea on how to address this use case thanks.

**Comment by Jason-Morcos** [comment]
Hi there, I'm not quite sure what your exact setup or use case is here, but I would surmise you can edit the automations you have set up with the occupancy plugin to either be disabled during the morning time, or to set the brightness to something less than 100%. Nowhere on the plugin side to I specify a brightness or anything, that's all the way you set up the automations in the home app that chooses brightness. 

I have some lights working with the plugin right now in my hallway that turn on with the occupancy plugin and they just resume their previous brightness level.

For light to turn on at a particular time of day, however, I wouldn't use this plugin. I would just set up an automation that's directly time-based, but perhaps I don't understand the exact setup. Maybe this is a case for https://www.reddit.com/r/homebridge/ :)

**Comment by Jason-Morcos** [comment]
Point 1 from this article may also be helpful? https://homekitnews.com/2020/08/31/best-homekit-automation-ideas-for-you-to-try/

**Comment by Pblondin123** [comment]
ok thanks i will do some testing using automations within a range of time during the day.
