### ISSUE TITLE
Trigger Stateless switch not turning back off

### ISSUE THREAD

**Issue by fightingmajor** [Jason-Morcos/homebridge-magic-occupancy#18]
I installed this last night and was trying to play around with it so I could use my two motion sensors in my bedroom along with the wall switch to turn on the lights by switch or motion and then turn everything off when there is no motion after X mins.  I've noticed that the Trigger Stateless Switch is not automatically turning off when it's turned on.

**Comment by Jason-Morcos** [comment]
Hey there, @fightingmajor, good catch! It looks like the last release I made an error in passing an argument to the off function which made the trigger switches stay on permanently. Checkout 3.1.3 and let me know if it fixes the issue!
