### ISSUE TITLE
Master shutoff switch - stateful

### ISSUE THREAD

**Issue by atlcoder** [Jason-Morcos/homebridge-magic-occupancy#21]
I want to use an occupancy sensor to control lights in a room, but I only want it to happen during certain times of day. Based on the description of the master shutoff switch, I assumed that I could turn on the master shutoff during the times of day that I don't want my occupancy sensor enabled. However, the master shutoff switch appears to work more like a stateless trigger than a stateful disable of the occupancy sensor.

Is there a way to do what I want with the existing switches, or would I need to add a stateful master shutoff switch as a separate type?

**Comment by Jason-Morcos** [comment]
Hey there! I actually have one I only use during the night - to do so, I just set up the automations for when occupancy starts and when occupancy ends to only be active during whatever hours you'd like in the home app directly

![IMG_4600](https://user-images.githubusercontent.com/10710367/151822192-5c5f2f18-61fe-4bc2-a116-9be2c6d5de55.PNG)

**Comment by atlcoder** [comment]
This works for the case where I want to turn on a light only during the evening. However there are other cases where I want to manually override the occupancy effect to be disabled, but not necessarily on any specific schedule. For example, I have a thermostat zone in my house that I want to normally control via occupancy, but if I have guests staying, I want to manually override the control (flip the master shutoff switch) until the guests leave. Is there some other trick to make that work?

**Comment by Jason-Morcos** [comment]
> This works for the case where I want to turn on a light only during the evening. However there are other cases where I want to manually override the occupancy effect to be disabled, but not necessarily on any specific schedule. For example, I have a thermostat zone in my house that I want to normally control via occupancy, but if I have guests staying, I want to manually override the control (flip the master shutoff switch) until the guests leave. Is there some other trick to make that work?

Yup!
Controller for HomeKit (https://apps.apple.com/us/app/controller-for-homekit/id1198176727), Eve, and other apps will let you make automations that only run when an event occurs (ex. Motion) _and_ some other switch is also on/off.
I created a "Guest Mode" switch using the dummy switch homebridge plug-in and I disable a bunch of stuff when that dummy switch is turned on with this trick :)

Example of turning off things when dummy switch is on:
![image](https://user-images.githubusercontent.com/10710367/152108954-f703b149-a374-498d-ab77-18807f6700fd.png)
