### ISSUE TITLE
Controlling lights in two rooms independently

### ISSUE THREAD

**Issue by Lampornis** [Jason-Morcos/homebridge-magic-occupancy#22]
I have set up an automation to turn lights on in both my wife’s yoga room and our master bedroom when motion is detected and for the lights to stay on as long as someone is in the room. The automation has three steps:

When motion is detected (either an Ecobee or Arqara motion sensor) turn on simple trigger switch activating the occupancy sensor.

When occupancy is detected turn on the lights (all Philips Hue).

When occupancy is no longer detected turn off the lights.

The automations are the same for both the yoga room and master bedroom except the rooms have different motion sensors and a different different trigger switch.

If I were only doing this in one room the automation works great! The problem I am having is that even though Magic Occupancy creates separate trigger switches for the two rooms it appears only one occupancy sensor is created so that whenever occupancy is detected in one room the lights for both rooms turn on. Been racking my brain trying to think of a solution for this without luck. Am I missing something or is this simply a limitation of the plugin? If you have thoughts on this I am all ears (or eyes). Thanks!!

**Comment by Jason-Morcos** [comment]
Hey! It sounds like you want the two rooms to be completely separate occupancy sensors? In that case, have you tried clicking the "Add Accessory" button in the plugin settings to create a totally separate occupancy sensor? Then, you can create separate switches for that occupancy sensor to control it and have one whole setup for each of the two rooms. For example, I have several different ones in my setup.

<img width="936" alt="Screen Shot 2022-02-28 at 21 09 17" src="https://user-images.githubusercontent.com/10710367/156108801-6b010f42-feec-4776-b28e-7f8ff6262879.png">
<img width="1010" alt="Screen Shot 2022-02-28 at 21 08 14" src="https://user-images.githubusercontent.com/10710367/156108803-a959f4c8-d544-484b-b8ee-f18a21df6e18.png">

**Comment by Lampornis** [comment]
Oh goodness, that was so rediculously easy.  Thank you so much!  I know this is a really simple thing, but I do not recall seeing anything about this in the documentation (I could very well have just missed it).  If it is not there you might consider adding a quick note about adding accessories.  Anyway, love the plugin.  It really was easy to set up.  Again, thanks!

**Comment by Jason-Morcos** [comment]
Good idea, I'll add a note, thanks!
