### ISSUE TITLE
Missing purpose in README.md

### ISSUE THREAD

**Issue by HolgerAusB** [Jason-Morcos/homebridge-magic-occupancy#32]
I just stumbled upon this plugin. But up to my not fluent English I was wondering what exactly is the purpose of this plugin and what is the magic thing about it.

In the README.md on github, right after the warning from upgrading v2 to v3, you should add one or two sentences to explain what this plugin is doing and what the magicial part is about.

**Comment by Jason-Morcos** [comment]
Added! Let me know if you have further questions
