### ISSUE TITLE
Feature Request: Set Log Level

### ISSUE THREAD

**Issue by Metatropics** [Jason-Morcos/homebridge-magic-occupancy#37]
Currently every action is logged, it'd be cool if we could increase or turn off verbosity.

**Comment by Jason-Morcos** [comment]
Pull requests welcome to add features! This is definitely a good idea to make logging better :)

**Comment by Metatropics** [comment]
🤔 Actually I've been looking to get into hb plugin dev and it seems very straightforward. Any pointers?

**Comment by Jason-Morcos** [comment]
It's definitely not too bad! I started with looking at a few plugins I liked and trying to figure out how they worked

**Comment by Metatropics** [comment]
done!

**Comment by clayoster** [comment]
I happened to have the idea to work on logging before finding this issue. Just submitted a PR. Hopefully it provides what you were looking for as well!

**Comment by robjampar** [comment]
@Jason-Morcos the PR above looks like it would solve this perfectly for me
