### ISSUE TITLE
Lost all sensors with new beta

### ISSUE THREAD

**Issue by darrenmcuk** [Jason-Morcos/homebridge-magic-occupancy#4]
Hi there,
Just loaded the new realise 2.41 and it caused the complete loss of all my sensors. Tried to roll back which brought them back but of course all the links to the automations were broke. Not sure what happened!

**Comment by Jason-Morcos** [comment]
Oh no! The 3.0.0 beta represents a pretty big change in configuration which will require some careful finesse for users to migrate to without losing all automations and configs. I just started work on the changes today and was flagging them as early betas so I hadn't got around to making any documentation around this (I usually do once changes stabilize)

It's this terrible HomeKit thing that if your switches disappear for even a second all of your automations are perpetually broken. It's happened to me twice and I never could find a way to revert back. I'm so sorry your automations were reset, I hope you don't have too many to recreate?

**Comment by darrenmcuk** [comment]
Just a few…these things happen. A bit of pain for this fantastic bit of work that’s going on here. If I reset the config will it now stay?

**Comment by Jason-Morcos** [comment]
If you reset the config with 2.x it should stay as long as you stay at 2.x! Same for 3 to 3

**Comment by darrenmcuk** [comment]
Perfect thanks.
