### ISSUE TITLE
What needs to happen in Home.app to make it work?

### ISSUE THREAD

**Issue by rh0dium** [Jason-Morcos/homebridge-magic-occupancy#49]
Is there anyway to provide a better example of turning off a light when no motion is detected.

Yes - I've read the docs and what I want appears to be in there but here is what's missing.  

Once you set up your config what needs to happen on the Home.app side of things.  After some digging I see my automations in a section called "An accessory is Controlled". What does a user need to do to enable them.

Perhaps you could provide a complete walkthrough for just to turn the switch off after _n_ minutes.

Thanks.

**Comment by rh0dium** [comment]
Oh man - I"m sorry.  After seeing a couple other implementations you do have it listed.  My Apologies.

**Comment by Jason-Morcos** [comment]
No worries! Glad you got it figured out :)
