### ISSUE TITLE
Motion Switch

### ISSUE THREAD

**Issue by swcc1197** [Jason-Morcos/homebridge-magic-occupancy#6]
I was on 3.0 beta and just updated to 14. The motion switch is now gone and not in the config.

**Comment by swcc1197** [comment]
Which after looking a second time I'm assuming just link the motion sensor to the trigger switch...

**Comment by Jason-Morcos** [comment]
Motion sensor is now == state full or trigger depending on your use case, yup! I use stateful and have it turned on when Motion starts and off when it stops.

**Comment by Jason-Morcos** [comment]
I'm still working on fully documenting out 3.0, but I think the latest beta is getting close. If you have any recommendations for things to make it clearer, I welcome them! :)
